### ISSUE TITLE
Add player count in status message

### ISSUE THREAD

**Issue by cafehaine** [Hetsh/mcsctl#25]
Hi,
I've been using mcsctl to manage a few servers for some months now, and I think that adding the player count to the status command's output could be a pretty nice qol improvement.
Thanks for your work!

**Comment by Hetsh** [comment]
Hi,
thanks for the great idea. After a quick google search i think the simplest solution is to send a [server list ping](https://wiki.vg/Server_List_Ping). A possibly fitting code [snippet using telnet](https://www.commandlinefu.com/commands/view/9647/get-number-of-users-on-a-minecraft-server) would be:
```bash
(echo -e '\xfe'; sleep 1) | telnet -L $HOSTIP 25565 2>/dev/null | awk -F '\xa7' '$2 {print "users: "$2"/"$3;}'
```
I need to test it, but it looks promising and should work out of the box.

**Comment by cafehaine** [comment]
Thanks a lot !

**Comment by Hetsh** [comment]
I am glad i can help :) and thank you for the idea!
The AUR package needs an urgent fix, before i can update it to the newest commit.

**Comment by Hetsh** [comment]
If you intend to switch or remove the mcsctl package please make a backup of the home directory.
I just realised that the home directory of the mcs user is wiped completely during package removal (i don't know why i thought this was a good idea).

**Comment by cafehaine** [comment]
Thanks for the tip ^^

**Comment by Hetsh** [comment]
This is fixed in both mcsctl and mcsctl-git packages. Please update them now before doing anything else.
Also mcsctl-git points to the latest commit if you want to test the new functionality.

**Comment by cafehaine** [comment]
I’ve got some issues with the upgrade and the new package :
- The user creation failed since the group "mcs" already existed from the previous version (not sure you can do anything about that)
- The package depends on "netcat", but uses -q which is only available in the openbsd-netcat package
- `mcsctl status all` gives me the following error from `jq`: 
![image](https://user-images.githubusercontent.com/11913365/81059493-cb195c00-8ed0-11ea-962f-29efe5d57245.png)

**Comment by Hetsh** [comment]
* there was a groupadd call previously, now there is just a --user-group flag with adduser. It shouldn't cause any harm.
* correct, i changed the dependency to openbsd-netcat
* which versions are your minecraft servers using?

**Comment by cafehaine** [comment]
1.14.2, I'm currently building multimc to check if it's not just the fact that nobody is only on my servers at this moment

**Comment by cafehaine** [comment]
![image](https://user-images.githubusercontent.com/11913365/81060619-22203080-8ed3-11ea-8464-1729ff458173.png)
Server 1 has no players
Server 2 has 1 player
And it's actually running 1.14.4, my bad

**Comment by Hetsh** [comment]
I cannot reproduce the error for your first server, but i can confirm that it is not working when a player is online. Please replace line 119 with the following snippet:
```bash
RESPONSE=$(echo -n -e '\x0f\x00\x2f\x09\x6c\x6f\x63\x61\x6c\x68\x6f\x73\x74\x63\xdd\x01\x01\x00' | nc -q 0 127.0.0.1 $((25564 + $SERVER_ID)) | cat -v - | sed 's/^[^{]*{/{/')
```
This fixes parsing for me, when players are online.

**Comment by cafehaine** [comment]
seems to fix the problem when no players are conected as well, so it’s perfect, thanks again!

**Comment by Hetsh** [comment]
mcsctl-git now contains the fix. Please submit more feature requests if you have more ideas.
