### ISSUE TITLE
Problem while I create a Server

### ISSUE THREAD

**Issue by xAspired** [Hetsh/mcsctl#26]
2022_01_15-17_00_29: MCServer #3: Creating server... /usr/bin/mcsctl: line 118: vercmp: command not found
/usr/bin/mcsctl: line 118: [: -ge: unary operator expected
done

Later that, If I start the server and I insert the "mcsctl console 2" command, it says to me that the server is not running.

**Comment by Hetsh** [comment]
Hi, the vercmp tool seems to be only available on Arch Linux... Which Distro are you using?

**Comment by Hetsh** [comment]
A simple equals operation would also do the trick... I'm going to change this.

**Comment by Hetsh** [comment]
Thanks for reporting! Does it now work as expected?

**Comment by xAspired** [comment]
> Thanks for reporting! Does it now work as expected?

I need to uninstall it and reinstall it again, am I wrong?

**Comment by Hetsh** [comment]
It is enough to replace the script manually.

**Comment by xAspired** [comment]
That what's happening
![Ex](https://i.postimg.cc/MTnNBWM1/Immagine-2022-01-16-234050.png)

**Comment by Hetsh** [comment]
I opened issue #27 for this problem. Please add the requested details.
