### ISSUE TITLE
Server fails to start

### ISSUE THREAD

**Issue by Hetsh** [Hetsh/mcsctl#27]
Derived from issue #26.

Logs suggest server is started, but it cannot be accessed:
```bash
[root@vps30561866 bin]# mcsctl start 6
2022_01_16-17_40_23: MCServer #6: Starting server... done
[root@vps30561866 bin]# mcsctl console 6
2022_01_16-17_40_28: MCServer #6: Server is not running!
```

**Comment by Hetsh** [comment]
@xAspired Please add some details:

- Which distro are you using
- what is the output of `ps -h`

**Comment by xAspired** [comment]
I am using CentOs 7.9.2009 (Core) and this is the output of ps -h:


```
[root@vps30561866 ~]# ps -h
  565 tty1     Ss+    0:00 /sbin/agetty --noclear tty1 linux
 5304 pts/0    Ss     0:00 -bash
 5325 pts/0    R+     0:00 ps -h
[root@vps30561866 ~]# 
```

Before I've installed the script, I installed the needed packet and then I inserted the commands for the "Non-Arch Linux Users".

**Comment by Hetsh** [comment]
Thanks, the installation steps are correct.
Sorry, I forgot to mention that you need to run `ps -h` as mcs user like this: `su mcs -s /bin/bash -c 'ps -h'`

**Comment by xAspired** [comment]
```
[root@vps30561866 ~]# su mcs -s /bin/bash -c 'ps -h'
19177 pts/1    Ss+    0:00 /bin/bash
24318 pts/2    Ss+    0:00 /bin/bash
30306 pts/3    Ss+    0:00 /bin/bash
32612 pts/4    Ss+    0:00 /bin/bash
[root@vps30561866 ~]# 
```

**Comment by Hetsh** [comment]
There is no java process. Are there any screen sessions? `su mcs -s /bin/bash -c 'screen -ls'`

**Comment by xAspired** [comment]
```
[root@vps30561866 ~]# su mcs -s /bin/bash -c 'screen -ls'
There are screens on:
        32608.mcserver6 (Detached)
        30302.mcserver4 (Detached)
        24314.mcserver2 (Detached)
        19176.mcserver1 (Detached)
4 Sockets in /var/run/screen/S-mcs.

[root@vps30561866 ~]# 
```

**Comment by Hetsh** [comment]
Please connect to one of the sessions `su mcs -s /bin/bash -c 'screen -r mcserver6'` and check for error messages. Post them here if there are any.

**Comment by Hetsh** [comment]
You can leave the screen session by typing `exit` like you would a normal shell.

**Comment by xAspired** [comment]
```
[mcs@vps30561866 mcserver2]$ cd "/home/mcs/mcserver2"; java -Xms1024M -Xmx1024M -jar "/home/mcs/mcserver2/server.jar" nogui
Error: A JNI error has occurred, please check your installation and try again
Exception in thread "main" java.lang.UnsupportedClassVersionError: net/minecraft/bundler/Main has been compiled by a more recent version of the Java Runtime (class file version 61.0), this version of the Java Runtime only recognizes class file versions up to 52.0
        at java.lang.ClassLoader.defineClass1(Native Method)
        at java.lang.ClassLoader.defineClass(ClassLoader.java:756)
        at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
        at java.net.URLClassLoader.defineClass(URLClassLoader.java:473)
        at java.net.URLClassLoader.access$100(URLClassLoader.java:74)
        at java.net.URLClassLoader$1.run(URLClassLoader.java:369)
        at java.net.URLClassLoader$1.run(URLClassLoader.java:363)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.net.URLClassLoader.findClass(URLClassLoader.java:362)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:418)
        at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:352)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:351)
        at sun.launcher.LauncherHelper.checkAndLoadMain(LauncherHelper.java:601)
[mcs@vps30561866 mcserver2]$ 
```

**Comment by Hetsh** [comment]
The java version seems to be outdated. Check with `java -version`. Minecraft needs openjdk version 16, see [this article](https://feedback.minecraft.net/hc/en-us/articles/4402626897165-Minecraft-Caves-Cliffs-Part-1-1-17-Java-).

**Comment by xAspired** [comment]
> The java version seems to be outdated. Check with `java -version`. Minecraft needs openjdk version 16, see [this article](https://feedback.minecraft.net/hc/en-us/articles/4402626897165-Minecraft-Caves-Cliffs-Part-1-1-17-Java-).

Now it seems work. Can I just use your script into an already existing servers? For example, instead of "mcserver1" "hub".

**Comment by Hetsh** [comment]
Great! I will try to put a check in place, so users get an error message if their java version is too old.

I can't give you a step by step tutorial, but if you manually copy the world files from "hub" to "mcserver1" it should work. You can't change the IDs, so you will still have to type e.g. `mcserver start 1` but the server name, that everybody else will see can be changed in the config file.

**Comment by xAspired** [comment]
> Great! I will try to put a check in place, so users get an error message if their java version is too old.
> 
> I can't give you a step by step tutorial, but if you manually copy the world files from "hub" to "mcserver1" it should work. You can't change the IDs, so you will still have to type e.g. `mcserver start 1` but the server name, that everybody else will see can be changed in the config file.

Thank you so much. I replaced the name and now works all fine. 
I removed from the mcsctl.conf file the "if" string.

**Comment by Hetsh** [comment]
Glad I could help :)

**Comment by xAspired** [comment]
> Glad I could help :)

Last question: Can I change the mcs user into another one?

**Comment by Hetsh** [comment]
This is not supported, but if you really want to change it you can:
Search for line `readonly MCS_USER="mcs"` in mcsctl.sh and change it. Be aware you have to change this every time you update mcsctl. You then also need to move the server files to the home directory of the new user and change the file permissions.

**Comment by xAspired** [comment]
> This is not supported, but if you really want to change it you can:
> 
> Search for line `readonly MCS_USER="mcs"` in mcsctl.sh and change it. Be aware you have to change this every time you update mcsctl. You then also need to move the server files to the home directory of the new user and change the file permissions.

Because I need to modify the files into the mcserver's folder with another user, and if I do it, the mcs user will not have permission to load plugin (for example).
Do you have any advice? I was thinking maybe or to change user of the script, or, if possible, assign a password for the mcs user and use that.

**Comment by Hetsh** [comment]
You can make your modifications as root and then grant the mcs user the necessary permissions with `chown -R mcs:mcs /home/mcs/<the_server_you_modified>`.

**Comment by xAspired** [comment]
Already did, but I need to do it every time I modify something.

**Comment by Hetsh** [comment]
To log in as mcs user, you have to unlock it and assign a password:
```
usermod --shell /bin/bash mcs
passwd -u mcs
passwd mcs
```
I am going to close this issue, since this conversation has nothing to do with the original issue any more.
