### ISSUE TITLE
Way to modify mcsctl.conf

### ISSUE THREAD

**Issue by xAspired** [Hetsh/mcsctl#28]
I am searching a way to insert an if into your config, but apparently I am wrong with some piece of code.
Basically I need to assign a certain number of ram for certain server (like the code below). Is that possible?

```
if [ -n "$SERVER_ID" ] && [ "$SERVER_ID" == "1" ]; then
        MIN_RAM="2048"
        MAX_RAM="2048"
        TIMEOUT="10"
        SERVER_ROOT="$HOME"
        DATE_FORMAT="%Y_%m_%d-%H_%M_%S"
fi

MIN_RAM="1024"
MAX_RAM="1024"
TIMEOUT="10"
SERVER_ROOT="$HOME"
DATE_FORMAT="%Y_%m_%d-%H_%M_%S"
```

**Comment by Hetsh** [comment]
Possible but not the default usecase. Your code looks fine on first glance. What do you mean with "you are wrong with some peice of code"? Is there an error message?

**Comment by xAspired** [comment]
Basically the server number one starts but his ram properties is 1024 instead of 2048. So I think that it never join the if condition.

**Comment by Hetsh** [comment]
Does your config look like your snippet? You have to put the 1024 RAM part above the 2048 RAM.

**Comment by Hetsh** [comment]
Please close this issue if that fixed your problem

**Comment by Hetsh** [comment]
Closed due to inactivity.

**Comment by Hetsh** [comment]
@peterfab9845 is currently working on a feature that allows this degree of customizability (see 364f483f56394fc6a8493bb87423dba98953bbcf)
